/*
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListWishlistsRequestFilter
 */
public class ListWishlistsRequestFilterTest {
    private final ListWishlistsRequestFilter model = new ListWishlistsRequestFilter();

    /**
     * Model tests for ListWishlistsRequestFilter
     */
    @Test
    public void testListWishlistsRequestFilter() {
        // TODO: test ListWishlistsRequestFilter
    }

    /**
     * Test the property 'customerGrn'
     */
    @Test
    public void customerGrnTest() {
        // TODO: test customerGrn
    }

}
