/*
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.WishlistWishlistResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WishlistListWishlistsResponse
 */
public class WishlistListWishlistsResponseTest {
    private final WishlistListWishlistsResponse model = new WishlistListWishlistsResponse();

    /**
     * Model tests for WishlistListWishlistsResponse
     */
    @Test
    public void testWishlistListWishlistsResponse() {
        // TODO: test WishlistListWishlistsResponse
    }

    /**
     * Test the property 'wishlist'
     */
    @Test
    public void wishlistTest() {
        // TODO: test wishlist
    }

    /**
     * Test the property 'nextPageToken'
     */
    @Test
    public void nextPageTokenTest() {
        // TODO: test nextPageToken
    }

}
