/*
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WishlistAreItemsInWishlistsRequest
 */
public class WishlistAreItemsInWishlistsRequestTest {
    private final WishlistAreItemsInWishlistsRequest model = new WishlistAreItemsInWishlistsRequest();

    /**
     * Model tests for WishlistAreItemsInWishlistsRequest
     */
    @Test
    public void testWishlistAreItemsInWishlistsRequest() {
        // TODO: test WishlistAreItemsInWishlistsRequest
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'wishlistId'
     */
    @Test
    public void wishlistIdTest() {
        // TODO: test wishlistId
    }

    /**
     * Test the property 'customerGrn'
     */
    @Test
    public void customerGrnTest() {
        // TODO: test customerGrn
    }

    /**
     * Test the property 'itemGrns'
     */
    @Test
    public void itemGrnsTest() {
        // TODO: test itemGrns
    }

}
