/*
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.WishlistLocalizedText;
import org.openapitools.client.model.WishlistPrivacy;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WishlistUpdateWishlistRequestPayload
 */
public class WishlistUpdateWishlistRequestPayloadTest {
    private final WishlistUpdateWishlistRequestPayload model = new WishlistUpdateWishlistRequestPayload();

    /**
     * Model tests for WishlistUpdateWishlistRequestPayload
     */
    @Test
    public void testWishlistUpdateWishlistRequestPayload() {
        // TODO: test WishlistUpdateWishlistRequestPayload
    }

    /**
     * Test the property 'privacy'
     */
    @Test
    public void privacyTest() {
        // TODO: test privacy
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'isDefault'
     */
    @Test
    public void isDefaultTest() {
        // TODO: test isDefault
    }

}
