/*
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WishlistBulkRemoveItemsFromWishlistsRequest
 */
public class WishlistBulkRemoveItemsFromWishlistsRequestTest {
    private final WishlistBulkRemoveItemsFromWishlistsRequest model = new WishlistBulkRemoveItemsFromWishlistsRequest();

    /**
     * Model tests for WishlistBulkRemoveItemsFromWishlistsRequest
     */
    @Test
    public void testWishlistBulkRemoveItemsFromWishlistsRequest() {
        // TODO: test WishlistBulkRemoveItemsFromWishlistsRequest
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'itemGrns'
     */
    @Test
    public void itemGrnsTest() {
        // TODO: test itemGrns
    }

    /**
     * Test the property 'wishlistIds'
     */
    @Test
    public void wishlistIdsTest() {
        // TODO: test wishlistIds
    }

}
