/*
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.WishlistSharingResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WishlistBulkCreateSharingResponse
 */
public class WishlistBulkCreateSharingResponseTest {
    private final WishlistBulkCreateSharingResponse model = new WishlistBulkCreateSharingResponse();

    /**
     * Model tests for WishlistBulkCreateSharingResponse
     */
    @Test
    public void testWishlistBulkCreateSharingResponse() {
        // TODO: test WishlistBulkCreateSharingResponse
    }

    /**
     * Test the property 'sharingResponses'
     */
    @Test
    public void sharingResponsesTest() {
        // TODO: test sharingResponses
    }

}
