/*
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.WishlistLocalizedText;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WishlistAddItemToWishlistRequest
 */
public class WishlistAddItemToWishlistRequestTest {
    private final WishlistAddItemToWishlistRequest model = new WishlistAddItemToWishlistRequest();

    /**
     * Model tests for WishlistAddItemToWishlistRequest
     */
    @Test
    public void testWishlistAddItemToWishlistRequest() {
        // TODO: test WishlistAddItemToWishlistRequest
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'wishlistId'
     */
    @Test
    public void wishlistIdTest() {
        // TODO: test wishlistId
    }

    /**
     * Test the property 'itemGrn'
     */
    @Test
    public void itemGrnTest() {
        // TODO: test itemGrn
    }

    /**
     * Test the property 'preferredQuantity'
     */
    @Test
    public void preferredQuantityTest() {
        // TODO: test preferredQuantity
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'customerGrn'
     */
    @Test
    public void customerGrnTest() {
        // TODO: test customerGrn
    }

}
