/*
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WishlistAreItemsInWishlistsResponsePayload
 */
public class WishlistAreItemsInWishlistsResponsePayloadTest {
    private final WishlistAreItemsInWishlistsResponsePayload model = new WishlistAreItemsInWishlistsResponsePayload();

    /**
     * Model tests for WishlistAreItemsInWishlistsResponsePayload
     */
    @Test
    public void testWishlistAreItemsInWishlistsResponsePayload() {
        // TODO: test WishlistAreItemsInWishlistsResponsePayload
    }

    /**
     * Test the property 'wishlistGrnToWishlistItemGrnMap'
     */
    @Test
    public void wishlistGrnToWishlistItemGrnMapTest() {
        // TODO: test wishlistGrnToWishlistItemGrnMap
    }

}
