/*
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.client.model.WishlistAreItemsInWishlistsResponsePayload;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WishlistAreItemsInWishlistsResponse
 */
public class WishlistAreItemsInWishlistsResponseTest {
    private final WishlistAreItemsInWishlistsResponse model = new WishlistAreItemsInWishlistsResponse();

    /**
     * Model tests for WishlistAreItemsInWishlistsResponse
     */
    @Test
    public void testWishlistAreItemsInWishlistsResponse() {
        // TODO: test WishlistAreItemsInWishlistsResponse
    }

    /**
     * Test the property 'itemGrnMap'
     */
    @Test
    public void itemGrnMapTest() {
        // TODO: test itemGrnMap
    }

}
