/*
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.WishlistPermission;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WishlistSharingRequest
 */
public class WishlistSharingRequestTest {
    private final WishlistSharingRequest model = new WishlistSharingRequest();

    /**
     * Model tests for WishlistSharingRequest
     */
    @Test
    public void testWishlistSharingRequest() {
        // TODO: test WishlistSharingRequest
    }

    /**
     * Test the property 'wishlistId'
     */
    @Test
    public void wishlistIdTest() {
        // TODO: test wishlistId
    }

    /**
     * Test the property 'permission'
     */
    @Test
    public void permissionTest() {
        // TODO: test permission
    }

    /**
     * Test the property 'customerGrn'
     */
    @Test
    public void customerGrnTest() {
        // TODO: test customerGrn
    }

    /**
     * Test the property 'customerAggregationId'
     */
    @Test
    public void customerAggregationIdTest() {
        // TODO: test customerAggregationId
    }

}
