/*
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.WishlistSharingRequest;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import GeminiCommerce_Wishlist.JSON;

/**
 * WishlistBulkCreateSharingRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-29T10:50:13.759631386Z[Etc/UTC]")
public class WishlistBulkCreateSharingRequest {
  public static final String SERIALIZED_NAME_TENANT_ID = "tenantId";
  @SerializedName(SERIALIZED_NAME_TENANT_ID)
  private String tenantId;

  public static final String SERIALIZED_NAME_SHARING_REQUESTS = "sharingRequests";
  @SerializedName(SERIALIZED_NAME_SHARING_REQUESTS)
  private List<WishlistSharingRequest> sharingRequests;

  public WishlistBulkCreateSharingRequest() {
  }

  public WishlistBulkCreateSharingRequest tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * Get tenantId
   * @return tenantId
  **/
  @javax.annotation.Nullable
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }


  public WishlistBulkCreateSharingRequest sharingRequests(List<WishlistSharingRequest> sharingRequests) {
    this.sharingRequests = sharingRequests;
    return this;
  }

  public WishlistBulkCreateSharingRequest addSharingRequestsItem(WishlistSharingRequest sharingRequestsItem) {
    if (this.sharingRequests == null) {
      this.sharingRequests = new ArrayList<>();
    }
    this.sharingRequests.add(sharingRequestsItem);
    return this;
  }

   /**
   * Get sharingRequests
   * @return sharingRequests
  **/
  @javax.annotation.Nullable
  public List<WishlistSharingRequest> getSharingRequests() {
    return sharingRequests;
  }

  public void setSharingRequests(List<WishlistSharingRequest> sharingRequests) {
    this.sharingRequests = sharingRequests;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WishlistBulkCreateSharingRequest wishlistBulkCreateSharingRequest = (WishlistBulkCreateSharingRequest) o;
    return Objects.equals(this.tenantId, wishlistBulkCreateSharingRequest.tenantId) &&
        Objects.equals(this.sharingRequests, wishlistBulkCreateSharingRequest.sharingRequests);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tenantId, sharingRequests);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WishlistBulkCreateSharingRequest {\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    sharingRequests: ").append(toIndentedString(sharingRequests)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("tenantId");
    openapiFields.add("sharingRequests");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to WishlistBulkCreateSharingRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WishlistBulkCreateSharingRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WishlistBulkCreateSharingRequest is not found in the empty JSON string", WishlistBulkCreateSharingRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!WishlistBulkCreateSharingRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `WishlistBulkCreateSharingRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("tenantId") != null && !jsonObj.get("tenantId").isJsonNull()) && !jsonObj.get("tenantId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tenantId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tenantId").toString()));
      }
      if (jsonObj.get("sharingRequests") != null && !jsonObj.get("sharingRequests").isJsonNull()) {
        JsonArray jsonArraysharingRequests = jsonObj.getAsJsonArray("sharingRequests");
        if (jsonArraysharingRequests != null) {
          // ensure the json data is an array
          if (!jsonObj.get("sharingRequests").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `sharingRequests` to be an array in the JSON string but got `%s`", jsonObj.get("sharingRequests").toString()));
          }

          // validate the optional field `sharingRequests` (array)
          for (int i = 0; i < jsonArraysharingRequests.size(); i++) {
            WishlistSharingRequest.validateJsonElement(jsonArraysharingRequests.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WishlistBulkCreateSharingRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WishlistBulkCreateSharingRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WishlistBulkCreateSharingRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WishlistBulkCreateSharingRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<WishlistBulkCreateSharingRequest>() {
           @Override
           public void write(JsonWriter out, WishlistBulkCreateSharingRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WishlistBulkCreateSharingRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of WishlistBulkCreateSharingRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of WishlistBulkCreateSharingRequest
  * @throws IOException if the JSON string is invalid with respect to WishlistBulkCreateSharingRequest
  */
  public static WishlistBulkCreateSharingRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WishlistBulkCreateSharingRequest.class);
  }

 /**
  * Convert an instance of WishlistBulkCreateSharingRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

