/*
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.WishlistLocalizedText;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import GeminiCommerce_Wishlist.JSON;

/**
 * WishlistUpdateItemInWishlistRequestPayload
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-29T10:50:13.759631386Z[Etc/UTC]")
public class WishlistUpdateItemInWishlistRequestPayload {
  public static final String SERIALIZED_NAME_PREFERRED_QUANTITY = "preferredQuantity";
  @SerializedName(SERIALIZED_NAME_PREFERRED_QUANTITY)
  private String preferredQuantity;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private WishlistLocalizedText description;

  public static final String SERIALIZED_NAME_CUSTOMER_GRN = "customerGrn";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_GRN)
  private String customerGrn;

  public WishlistUpdateItemInWishlistRequestPayload() {
  }

  public WishlistUpdateItemInWishlistRequestPayload preferredQuantity(String preferredQuantity) {
    this.preferredQuantity = preferredQuantity;
    return this;
  }

   /**
   * Get preferredQuantity
   * @return preferredQuantity
  **/
  @javax.annotation.Nullable
  public String getPreferredQuantity() {
    return preferredQuantity;
  }

  public void setPreferredQuantity(String preferredQuantity) {
    this.preferredQuantity = preferredQuantity;
  }


  public WishlistUpdateItemInWishlistRequestPayload description(WishlistLocalizedText description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  public WishlistLocalizedText getDescription() {
    return description;
  }

  public void setDescription(WishlistLocalizedText description) {
    this.description = description;
  }


  public WishlistUpdateItemInWishlistRequestPayload customerGrn(String customerGrn) {
    this.customerGrn = customerGrn;
    return this;
  }

   /**
   * Get customerGrn
   * @return customerGrn
  **/
  @javax.annotation.Nullable
  public String getCustomerGrn() {
    return customerGrn;
  }

  public void setCustomerGrn(String customerGrn) {
    this.customerGrn = customerGrn;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WishlistUpdateItemInWishlistRequestPayload wishlistUpdateItemInWishlistRequestPayload = (WishlistUpdateItemInWishlistRequestPayload) o;
    return Objects.equals(this.preferredQuantity, wishlistUpdateItemInWishlistRequestPayload.preferredQuantity) &&
        Objects.equals(this.description, wishlistUpdateItemInWishlistRequestPayload.description) &&
        Objects.equals(this.customerGrn, wishlistUpdateItemInWishlistRequestPayload.customerGrn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(preferredQuantity, description, customerGrn);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WishlistUpdateItemInWishlistRequestPayload {\n");
    sb.append("    preferredQuantity: ").append(toIndentedString(preferredQuantity)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    customerGrn: ").append(toIndentedString(customerGrn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("preferredQuantity");
    openapiFields.add("description");
    openapiFields.add("customerGrn");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to WishlistUpdateItemInWishlistRequestPayload
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WishlistUpdateItemInWishlistRequestPayload.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WishlistUpdateItemInWishlistRequestPayload is not found in the empty JSON string", WishlistUpdateItemInWishlistRequestPayload.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!WishlistUpdateItemInWishlistRequestPayload.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `WishlistUpdateItemInWishlistRequestPayload` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("preferredQuantity") != null && !jsonObj.get("preferredQuantity").isJsonNull()) && !jsonObj.get("preferredQuantity").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `preferredQuantity` to be a primitive type in the JSON string but got `%s`", jsonObj.get("preferredQuantity").toString()));
      }
      // validate the optional field `description`
      if (jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) {
        WishlistLocalizedText.validateJsonElement(jsonObj.get("description"));
      }
      if ((jsonObj.get("customerGrn") != null && !jsonObj.get("customerGrn").isJsonNull()) && !jsonObj.get("customerGrn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `customerGrn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customerGrn").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WishlistUpdateItemInWishlistRequestPayload.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WishlistUpdateItemInWishlistRequestPayload' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WishlistUpdateItemInWishlistRequestPayload> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WishlistUpdateItemInWishlistRequestPayload.class));

       return (TypeAdapter<T>) new TypeAdapter<WishlistUpdateItemInWishlistRequestPayload>() {
           @Override
           public void write(JsonWriter out, WishlistUpdateItemInWishlistRequestPayload value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WishlistUpdateItemInWishlistRequestPayload read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of WishlistUpdateItemInWishlistRequestPayload given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of WishlistUpdateItemInWishlistRequestPayload
  * @throws IOException if the JSON string is invalid with respect to WishlistUpdateItemInWishlistRequestPayload
  */
  public static WishlistUpdateItemInWishlistRequestPayload fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WishlistUpdateItemInWishlistRequestPayload.class);
  }

 /**
  * Convert an instance of WishlistUpdateItemInWishlistRequestPayload to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

