/*
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import GeminiCommerce_Wishlist.JSON;

/**
 * WishlistAreItemsInWishlistsResponsePayload
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-29T10:50:13.759631386Z[Etc/UTC]")
public class WishlistAreItemsInWishlistsResponsePayload {
  public static final String SERIALIZED_NAME_WISHLIST_GRN_TO_WISHLIST_ITEM_GRN_MAP = "wishlistGrnToWishlistItemGrnMap";
  @SerializedName(SERIALIZED_NAME_WISHLIST_GRN_TO_WISHLIST_ITEM_GRN_MAP)
  private Map<String, String> wishlistGrnToWishlistItemGrnMap = new HashMap<>();

  public WishlistAreItemsInWishlistsResponsePayload() {
  }

  public WishlistAreItemsInWishlistsResponsePayload wishlistGrnToWishlistItemGrnMap(Map<String, String> wishlistGrnToWishlistItemGrnMap) {
    this.wishlistGrnToWishlistItemGrnMap = wishlistGrnToWishlistItemGrnMap;
    return this;
  }

  public WishlistAreItemsInWishlistsResponsePayload putWishlistGrnToWishlistItemGrnMapItem(String key, String wishlistGrnToWishlistItemGrnMapItem) {
    if (this.wishlistGrnToWishlistItemGrnMap == null) {
      this.wishlistGrnToWishlistItemGrnMap = new HashMap<>();
    }
    this.wishlistGrnToWishlistItemGrnMap.put(key, wishlistGrnToWishlistItemGrnMapItem);
    return this;
  }

   /**
   * Get wishlistGrnToWishlistItemGrnMap
   * @return wishlistGrnToWishlistItemGrnMap
  **/
  @javax.annotation.Nullable
  public Map<String, String> getWishlistGrnToWishlistItemGrnMap() {
    return wishlistGrnToWishlistItemGrnMap;
  }

  public void setWishlistGrnToWishlistItemGrnMap(Map<String, String> wishlistGrnToWishlistItemGrnMap) {
    this.wishlistGrnToWishlistItemGrnMap = wishlistGrnToWishlistItemGrnMap;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WishlistAreItemsInWishlistsResponsePayload wishlistAreItemsInWishlistsResponsePayload = (WishlistAreItemsInWishlistsResponsePayload) o;
    return Objects.equals(this.wishlistGrnToWishlistItemGrnMap, wishlistAreItemsInWishlistsResponsePayload.wishlistGrnToWishlistItemGrnMap);
  }

  @Override
  public int hashCode() {
    return Objects.hash(wishlistGrnToWishlistItemGrnMap);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WishlistAreItemsInWishlistsResponsePayload {\n");
    sb.append("    wishlistGrnToWishlistItemGrnMap: ").append(toIndentedString(wishlistGrnToWishlistItemGrnMap)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("wishlistGrnToWishlistItemGrnMap");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to WishlistAreItemsInWishlistsResponsePayload
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WishlistAreItemsInWishlistsResponsePayload.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WishlistAreItemsInWishlistsResponsePayload is not found in the empty JSON string", WishlistAreItemsInWishlistsResponsePayload.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!WishlistAreItemsInWishlistsResponsePayload.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `WishlistAreItemsInWishlistsResponsePayload` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WishlistAreItemsInWishlistsResponsePayload.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WishlistAreItemsInWishlistsResponsePayload' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WishlistAreItemsInWishlistsResponsePayload> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WishlistAreItemsInWishlistsResponsePayload.class));

       return (TypeAdapter<T>) new TypeAdapter<WishlistAreItemsInWishlistsResponsePayload>() {
           @Override
           public void write(JsonWriter out, WishlistAreItemsInWishlistsResponsePayload value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WishlistAreItemsInWishlistsResponsePayload read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of WishlistAreItemsInWishlistsResponsePayload given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of WishlistAreItemsInWishlistsResponsePayload
  * @throws IOException if the JSON string is invalid with respect to WishlistAreItemsInWishlistsResponsePayload
  */
  public static WishlistAreItemsInWishlistsResponsePayload fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WishlistAreItemsInWishlistsResponsePayload.class);
  }

 /**
  * Convert an instance of WishlistAreItemsInWishlistsResponsePayload to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

