/*
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.WishlistWishlistResponse;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import GeminiCommerce_Wishlist.JSON;

/**
 * WishlistListWishlistsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-29T10:50:13.759631386Z[Etc/UTC]")
public class WishlistListWishlistsResponse {
  public static final String SERIALIZED_NAME_WISHLIST = "wishlist";
  @SerializedName(SERIALIZED_NAME_WISHLIST)
  private List<WishlistWishlistResponse> wishlist;

  public static final String SERIALIZED_NAME_NEXT_PAGE_TOKEN = "nextPageToken";
  @SerializedName(SERIALIZED_NAME_NEXT_PAGE_TOKEN)
  private String nextPageToken;

  public WishlistListWishlistsResponse() {
  }

  public WishlistListWishlistsResponse wishlist(List<WishlistWishlistResponse> wishlist) {
    this.wishlist = wishlist;
    return this;
  }

  public WishlistListWishlistsResponse addWishlistItem(WishlistWishlistResponse wishlistItem) {
    if (this.wishlist == null) {
      this.wishlist = new ArrayList<>();
    }
    this.wishlist.add(wishlistItem);
    return this;
  }

   /**
   * Get wishlist
   * @return wishlist
  **/
  @javax.annotation.Nullable
  public List<WishlistWishlistResponse> getWishlist() {
    return wishlist;
  }

  public void setWishlist(List<WishlistWishlistResponse> wishlist) {
    this.wishlist = wishlist;
  }


  public WishlistListWishlistsResponse nextPageToken(String nextPageToken) {
    this.nextPageToken = nextPageToken;
    return this;
  }

   /**
   * Get nextPageToken
   * @return nextPageToken
  **/
  @javax.annotation.Nullable
  public String getNextPageToken() {
    return nextPageToken;
  }

  public void setNextPageToken(String nextPageToken) {
    this.nextPageToken = nextPageToken;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WishlistListWishlistsResponse wishlistListWishlistsResponse = (WishlistListWishlistsResponse) o;
    return Objects.equals(this.wishlist, wishlistListWishlistsResponse.wishlist) &&
        Objects.equals(this.nextPageToken, wishlistListWishlistsResponse.nextPageToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(wishlist, nextPageToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WishlistListWishlistsResponse {\n");
    sb.append("    wishlist: ").append(toIndentedString(wishlist)).append("\n");
    sb.append("    nextPageToken: ").append(toIndentedString(nextPageToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("wishlist");
    openapiFields.add("nextPageToken");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to WishlistListWishlistsResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WishlistListWishlistsResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WishlistListWishlistsResponse is not found in the empty JSON string", WishlistListWishlistsResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!WishlistListWishlistsResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `WishlistListWishlistsResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("wishlist") != null && !jsonObj.get("wishlist").isJsonNull()) {
        JsonArray jsonArraywishlist = jsonObj.getAsJsonArray("wishlist");
        if (jsonArraywishlist != null) {
          // ensure the json data is an array
          if (!jsonObj.get("wishlist").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `wishlist` to be an array in the JSON string but got `%s`", jsonObj.get("wishlist").toString()));
          }

          // validate the optional field `wishlist` (array)
          for (int i = 0; i < jsonArraywishlist.size(); i++) {
            WishlistWishlistResponse.validateJsonElement(jsonArraywishlist.get(i));
          };
        }
      }
      if ((jsonObj.get("nextPageToken") != null && !jsonObj.get("nextPageToken").isJsonNull()) && !jsonObj.get("nextPageToken").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nextPageToken` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nextPageToken").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WishlistListWishlistsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WishlistListWishlistsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WishlistListWishlistsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WishlistListWishlistsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<WishlistListWishlistsResponse>() {
           @Override
           public void write(JsonWriter out, WishlistListWishlistsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WishlistListWishlistsResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of WishlistListWishlistsResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of WishlistListWishlistsResponse
  * @throws IOException if the JSON string is invalid with respect to WishlistListWishlistsResponse
  */
  public static WishlistListWishlistsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WishlistListWishlistsResponse.class);
  }

 /**
  * Convert an instance of WishlistListWishlistsResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

