/*
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.WishlistSharingResponse;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import GeminiCommerce_Wishlist.JSON;

/**
 * WishlistBulkCreateSharingResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-29T10:50:13.759631386Z[Etc/UTC]")
public class WishlistBulkCreateSharingResponse {
  public static final String SERIALIZED_NAME_SHARING_RESPONSES = "sharingResponses";
  @SerializedName(SERIALIZED_NAME_SHARING_RESPONSES)
  private List<WishlistSharingResponse> sharingResponses;

  public WishlistBulkCreateSharingResponse() {
  }

  public WishlistBulkCreateSharingResponse sharingResponses(List<WishlistSharingResponse> sharingResponses) {
    this.sharingResponses = sharingResponses;
    return this;
  }

  public WishlistBulkCreateSharingResponse addSharingResponsesItem(WishlistSharingResponse sharingResponsesItem) {
    if (this.sharingResponses == null) {
      this.sharingResponses = new ArrayList<>();
    }
    this.sharingResponses.add(sharingResponsesItem);
    return this;
  }

   /**
   * Get sharingResponses
   * @return sharingResponses
  **/
  @javax.annotation.Nullable
  public List<WishlistSharingResponse> getSharingResponses() {
    return sharingResponses;
  }

  public void setSharingResponses(List<WishlistSharingResponse> sharingResponses) {
    this.sharingResponses = sharingResponses;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WishlistBulkCreateSharingResponse wishlistBulkCreateSharingResponse = (WishlistBulkCreateSharingResponse) o;
    return Objects.equals(this.sharingResponses, wishlistBulkCreateSharingResponse.sharingResponses);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sharingResponses);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WishlistBulkCreateSharingResponse {\n");
    sb.append("    sharingResponses: ").append(toIndentedString(sharingResponses)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("sharingResponses");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to WishlistBulkCreateSharingResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WishlistBulkCreateSharingResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WishlistBulkCreateSharingResponse is not found in the empty JSON string", WishlistBulkCreateSharingResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!WishlistBulkCreateSharingResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `WishlistBulkCreateSharingResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("sharingResponses") != null && !jsonObj.get("sharingResponses").isJsonNull()) {
        JsonArray jsonArraysharingResponses = jsonObj.getAsJsonArray("sharingResponses");
        if (jsonArraysharingResponses != null) {
          // ensure the json data is an array
          if (!jsonObj.get("sharingResponses").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `sharingResponses` to be an array in the JSON string but got `%s`", jsonObj.get("sharingResponses").toString()));
          }

          // validate the optional field `sharingResponses` (array)
          for (int i = 0; i < jsonArraysharingResponses.size(); i++) {
            WishlistSharingResponse.validateJsonElement(jsonArraysharingResponses.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WishlistBulkCreateSharingResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WishlistBulkCreateSharingResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WishlistBulkCreateSharingResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WishlistBulkCreateSharingResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<WishlistBulkCreateSharingResponse>() {
           @Override
           public void write(JsonWriter out, WishlistBulkCreateSharingResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WishlistBulkCreateSharingResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of WishlistBulkCreateSharingResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of WishlistBulkCreateSharingResponse
  * @throws IOException if the JSON string is invalid with respect to WishlistBulkCreateSharingResponse
  */
  public static WishlistBulkCreateSharingResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WishlistBulkCreateSharingResponse.class);
  }

 /**
  * Convert an instance of WishlistBulkCreateSharingResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

