/*
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.WishlistSharingResponse;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import GeminiCommerce.Wishlist.JSON;

/**
 * WishlistBulkCreateSharingResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-14T11:43:44.768236855Z[Etc/UTC]", comments = "Generator version: 7.9.0")
public class WishlistBulkCreateSharingResponse {
  public static final String SERIALIZED_NAME_SHARING_RESPONSES = "sharingResponses";
  @SerializedName(SERIALIZED_NAME_SHARING_RESPONSES)
  private List<WishlistSharingResponse> sharingResponses = new ArrayList<>();

  public WishlistBulkCreateSharingResponse() {
  }

  public WishlistBulkCreateSharingResponse sharingResponses(List<WishlistSharingResponse> sharingResponses) {
    this.sharingResponses = sharingResponses;
    return this;
  }

  public WishlistBulkCreateSharingResponse addSharingResponsesItem(WishlistSharingResponse sharingResponsesItem) {
    if (this.sharingResponses == null) {
      this.sharingResponses = new ArrayList<>();
    }
    this.sharingResponses.add(sharingResponsesItem);
    return this;
  }

  /**
   * Get sharingResponses
   * @return sharingResponses
   */
  @javax.annotation.Nullable
  public List<WishlistSharingResponse> getSharingResponses() {
    return sharingResponses;
  }

  public void setSharingResponses(List<WishlistSharingResponse> sharingResponses) {
    this.sharingResponses = sharingResponses;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the WishlistBulkCreateSharingResponse instance itself
   */
  public WishlistBulkCreateSharingResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WishlistBulkCreateSharingResponse wishlistBulkCreateSharingResponse = (WishlistBulkCreateSharingResponse) o;
    return Objects.equals(this.sharingResponses, wishlistBulkCreateSharingResponse.sharingResponses)&&
        Objects.equals(this.additionalProperties, wishlistBulkCreateSharingResponse.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sharingResponses, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WishlistBulkCreateSharingResponse {\n");
    sb.append("    sharingResponses: ").append(toIndentedString(sharingResponses)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("sharingResponses");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WishlistBulkCreateSharingResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WishlistBulkCreateSharingResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WishlistBulkCreateSharingResponse is not found in the empty JSON string", WishlistBulkCreateSharingResponse.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("sharingResponses") != null && !jsonObj.get("sharingResponses").isJsonNull()) {
        JsonArray jsonArraysharingResponses = jsonObj.getAsJsonArray("sharingResponses");
        if (jsonArraysharingResponses != null) {
          // ensure the json data is an array
          if (!jsonObj.get("sharingResponses").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `sharingResponses` to be an array in the JSON string but got `%s`", jsonObj.get("sharingResponses").toString()));
          }

          // validate the optional field `sharingResponses` (array)
          for (int i = 0; i < jsonArraysharingResponses.size(); i++) {
            WishlistSharingResponse.validateJsonElement(jsonArraysharingResponses.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WishlistBulkCreateSharingResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WishlistBulkCreateSharingResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WishlistBulkCreateSharingResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WishlistBulkCreateSharingResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<WishlistBulkCreateSharingResponse>() {
           @Override
           public void write(JsonWriter out, WishlistBulkCreateSharingResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public WishlistBulkCreateSharingResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             WishlistBulkCreateSharingResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WishlistBulkCreateSharingResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WishlistBulkCreateSharingResponse
   * @throws IOException if the JSON string is invalid with respect to WishlistBulkCreateSharingResponse
   */
  public static WishlistBulkCreateSharingResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WishlistBulkCreateSharingResponse.class);
  }

  /**
   * Convert an instance of WishlistBulkCreateSharingResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

