/*
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import GeminiCommerce_Wishlist.JSON;

/**
 * WishlistMergeWishlistsRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-29T10:50:13.759631386Z[Etc/UTC]")
public class WishlistMergeWishlistsRequest {
  public static final String SERIALIZED_NAME_TENANT_ID = "tenantId";
  @SerializedName(SERIALIZED_NAME_TENANT_ID)
  private String tenantId;

  public static final String SERIALIZED_NAME_STARTING_WISHLIST_ID = "startingWishlistId";
  @SerializedName(SERIALIZED_NAME_STARTING_WISHLIST_ID)
  private String startingWishlistId;

  public static final String SERIALIZED_NAME_CUSTOMER_GRN = "customerGrn";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_GRN)
  private String customerGrn;

  public static final String SERIALIZED_NAME_TARGET_WISHLIST_ID = "targetWishlistId";
  @SerializedName(SERIALIZED_NAME_TARGET_WISHLIST_ID)
  private String targetWishlistId;

  public WishlistMergeWishlistsRequest() {
  }

  public WishlistMergeWishlistsRequest tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * Get tenantId
   * @return tenantId
  **/
  @javax.annotation.Nonnull
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }


  public WishlistMergeWishlistsRequest startingWishlistId(String startingWishlistId) {
    this.startingWishlistId = startingWishlistId;
    return this;
  }

   /**
   * Get startingWishlistId
   * @return startingWishlistId
  **/
  @javax.annotation.Nonnull
  public String getStartingWishlistId() {
    return startingWishlistId;
  }

  public void setStartingWishlistId(String startingWishlistId) {
    this.startingWishlistId = startingWishlistId;
  }


  public WishlistMergeWishlistsRequest customerGrn(String customerGrn) {
    this.customerGrn = customerGrn;
    return this;
  }

   /**
   * If the customer GRN is set on JWT, it will be used as default. Otherwise, it will be used the customer_grn field.
   * @return customerGrn
  **/
  @javax.annotation.Nonnull
  public String getCustomerGrn() {
    return customerGrn;
  }

  public void setCustomerGrn(String customerGrn) {
    this.customerGrn = customerGrn;
  }


  public WishlistMergeWishlistsRequest targetWishlistId(String targetWishlistId) {
    this.targetWishlistId = targetWishlistId;
    return this;
  }

   /**
   * The wishlist to merge into the starting wishlist.
   * @return targetWishlistId
  **/
  @javax.annotation.Nullable
  public String getTargetWishlistId() {
    return targetWishlistId;
  }

  public void setTargetWishlistId(String targetWishlistId) {
    this.targetWishlistId = targetWishlistId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WishlistMergeWishlistsRequest wishlistMergeWishlistsRequest = (WishlistMergeWishlistsRequest) o;
    return Objects.equals(this.tenantId, wishlistMergeWishlistsRequest.tenantId) &&
        Objects.equals(this.startingWishlistId, wishlistMergeWishlistsRequest.startingWishlistId) &&
        Objects.equals(this.customerGrn, wishlistMergeWishlistsRequest.customerGrn) &&
        Objects.equals(this.targetWishlistId, wishlistMergeWishlistsRequest.targetWishlistId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tenantId, startingWishlistId, customerGrn, targetWishlistId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WishlistMergeWishlistsRequest {\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    startingWishlistId: ").append(toIndentedString(startingWishlistId)).append("\n");
    sb.append("    customerGrn: ").append(toIndentedString(customerGrn)).append("\n");
    sb.append("    targetWishlistId: ").append(toIndentedString(targetWishlistId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("tenantId");
    openapiFields.add("startingWishlistId");
    openapiFields.add("customerGrn");
    openapiFields.add("targetWishlistId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("tenantId");
    openapiRequiredFields.add("startingWishlistId");
    openapiRequiredFields.add("customerGrn");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to WishlistMergeWishlistsRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WishlistMergeWishlistsRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WishlistMergeWishlistsRequest is not found in the empty JSON string", WishlistMergeWishlistsRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!WishlistMergeWishlistsRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `WishlistMergeWishlistsRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : WishlistMergeWishlistsRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("tenantId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tenantId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tenantId").toString()));
      }
      if (!jsonObj.get("startingWishlistId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `startingWishlistId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("startingWishlistId").toString()));
      }
      if (!jsonObj.get("customerGrn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `customerGrn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customerGrn").toString()));
      }
      if ((jsonObj.get("targetWishlistId") != null && !jsonObj.get("targetWishlistId").isJsonNull()) && !jsonObj.get("targetWishlistId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `targetWishlistId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("targetWishlistId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WishlistMergeWishlistsRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WishlistMergeWishlistsRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WishlistMergeWishlistsRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WishlistMergeWishlistsRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<WishlistMergeWishlistsRequest>() {
           @Override
           public void write(JsonWriter out, WishlistMergeWishlistsRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WishlistMergeWishlistsRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of WishlistMergeWishlistsRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of WishlistMergeWishlistsRequest
  * @throws IOException if the JSON string is invalid with respect to WishlistMergeWishlistsRequest
  */
  public static WishlistMergeWishlistsRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WishlistMergeWishlistsRequest.class);
  }

 /**
  * Convert an instance of WishlistMergeWishlistsRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

