/*
 * Wishlist Service
 * API for managing wishlists
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets wishlistPrivacy
 */
@JsonAdapter(WishlistPrivacy.Adapter.class)
public enum WishlistPrivacy {
  
  UNKNOWN("PRIVACY_UNKNOWN"),
  
  PUBLIC("PRIVACY_PUBLIC"),
  
  PRIVATE("PRIVACY_PRIVATE"),
  
  SHARED("PRIVACY_SHARED");

  private String value;

  WishlistPrivacy(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static WishlistPrivacy fromValue(String value) {
    for (WishlistPrivacy b : WishlistPrivacy.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<WishlistPrivacy> {
    @Override
    public void write(final JsonWriter jsonWriter, final WishlistPrivacy enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public WishlistPrivacy read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return WishlistPrivacy.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    WishlistPrivacy.fromValue(value);
  }
}

